Vermont Oxford Network (VON) is a nonprofit voluntary collaboration of health care professionals working together as an interdisciplinary community to change the landscape of neonatal care.  Founded in 1988, VON is now comprised of teams of health professionals representing neonatal intensive care units and level I and II care centers around the world, in support of the mission to improve the quality and safety of medical care for newborn infants and their families through a coordinated program of research, education, and quality improvement projects. (ref: https://public.vtoxford.org/about-us/)

Mortality Risk Amongst Very Low Birth Weight Infants Born in the Republic of Ireland was published by  National Perinatal Epidemiology Centre, 2018 (ref: 
https://www.ucc.ie/en/media/research/nationalperinatalepidemiologycentre/annualreports/MortalityRiskAmongstVeryLowBirthWeightInfantsintheRepublicofIrelandReport2014-2016.pdf)

This notebook aims to sythesise data to reflect the findings in this report

# The Variables - Explained

## Gestational Weeks
Gestational age is the common term used during pregnancy to describe how far along the pregnancy is. It is measured in weeks, from the first day of the woman's last menstrual cycle to the current date. A normal pregnancy can range from 38 to 42 weeks. Infants born before 37 weeks are considered premature. The outcome of this variable will be most likely between 22 - 32 weeks.
(ref:https://medlineplus.gov/ency/article/002367.htm)

## Birthweight
Birth weight is the first weight of your baby, taken just after he or she is born. A low birth weight is less than 5.5 pounds. A high birth weight is more than 8.8 pounds. The expected result of this variable will see most weights less than 5.5 pounds 

## Congenital Anomaly 
Congenital anomalies are also known as birth defects, congenital disorders or congenital malformations. Yes or No.

## Disposition at 1 Year
Did the infant live or die.  The outcome is recorded one year after birth.  There are 4 possible outcomes:
- Died
- Home
- Still Hospitalised
- Unkown
 



In [26]:
# create a dataframe structure by starting with the column headings
import pandas as pd
import numpy as np
df = pd.DataFrame(columns= ["Gestational Weeks", "Birthweight", "Congenital Anomaly", "Disposition at 1 Year" ])

In [15]:
df

Empty DataFrame
Columns: [Index, Gestational Weeks, Birthweight, Congenital Anomaly, Disposition at 1 Year]
Index: []

In [24]:
# Testing to populate the data 
data = [['Alex',10, 6, 2],['Bob',12, 6 ,2],['Clarke',13, 6 ,2]]
df = pd.DataFrame(data, columns = ['Gestational Weeks', 'Birthweight', 'Congenital Anomaly', 'Disposition at 1 Year'])
df

Gestational Weeks  Birthweight  Congenital Anomaly  Disposition at 1 Year
0              Alex           10                   6                      2
1               Bob           12                   6                      2
2            Clarke           13                   6                      2

In [27]:
# The above table is the basic structure which I will use as the foundations for systhessing my dataset

## Gestational Weeks
In this dataset the Gestational weeks has a spread from 21 weeks to 33 weeks.


In [36]:
#Setting Parameters for gestational weeks.  Majority of babies born weeks 28, 29, 30
mu, sigma = 28, 3 # mean and standard deviation
gw = np.random.normal(mu, sigma, 100) 
gw

array([29.69768504, 24.76739034, 25.53623763, 27.26828616, 29.59302257,
       25.3373349 , 29.54341044, 36.15830912, 30.59832384, 27.74739893,
       27.47888197, 27.77545595, 30.81360771, 26.91865339, 30.38561703,
       31.97756924, 26.40315956, 25.29837499, 24.80605937, 24.84813743,
       28.83754857, 29.26610866, 30.82146422, 29.11268851, 32.25257221,
       23.29492779, 25.56522894, 27.11744117, 27.39699415, 23.67425756,
       26.91146859, 25.69598078, 25.62514379, 29.69177789, 29.53570556,
       29.75994977, 30.97226271, 24.36231541, 26.32600429, 22.0893333 ,
       27.58096215, 26.33505857, 30.7548689 , 25.17517032, 31.53426665,
       29.62151495, 28.52543361, 30.91486687, 37.78047092, 28.33404991,
       27.60450218, 24.5385594 , 26.05133773, 33.56249583, 25.04210597,
       30.7471004 , 32.6188011 , 27.60230501, 25.27491328, 25.54236253,
       24.93176192, 32.02557391, 24.33906971, 24.7718252 , 25.67493756,
       29.34498388, 26.30362328, 27.37844447, 29.85610213, 24.49

## Birthweight
The birth weights of very low birth weight infants ranged from
360g to 2,640g

In [34]:
#Setting Parameters for bithweight, low = 400g, High = 1500g

bw = np.random.randint(400, 1500, size=100) #this function draws random numbers from a uniform distribution
bw

array([ 993, 1103,  922, 1125,  686, 1149,  552, 1449,  666, 1105, 1313,
        733,  509,  889, 1285,  806,  955,  641, 1287,  481, 1120, 1204,
       1496,  588,  416,  523, 1265,  717,  755,  926,  804,  965,  966,
        427, 1220,  649, 1381,  417,  526,  595, 1184,  819, 1063, 1386,
        854, 1460,  705,  555,  862, 1453,  582, 1351, 1377, 1171, 1103,
       1260,  403,  467,  641, 1198,  666,  653, 1196, 1144,  949,  827,
       1297, 1200,  729,  870, 1394,  580,  437, 1266, 1439, 1263, 1027,
       1191,  445,  601,  486, 1447,  789,  746, 1149,  704,  868,  570,
        665, 1411, 1444,  883, 1115,  731, 1490,  400, 1465, 1047,  737,
        796])

## Congenital Anomaly
8.3% of babies have a congenital anomaly.  Yes or No Answer

In [41]:
x = np.random.randint(0, 2, 100)
x


array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1])