Vermont Oxford Network (VON) is a nonprofit voluntary collaboration of health care professionals working together as an interdisciplinary community to change the landscape of neonatal care.  Founded in 1988, VON is now comprised of teams of health professionals representing neonatal intensive care units and level I and II care centers around the world, in support of the mission to improve the quality and safety of medical care for newborn infants and their families through a coordinated program of research, education, and quality improvement projects. (ref: https://public.vtoxford.org/about-us/)

Mortality Risk Amongst Very Low Birth Weight Infants Born in the Republic of Ireland was published by  National Perinatal Epidemiology Centre, 2018 (ref: 
https://www.ucc.ie/en/media/research/nationalperinatalepidemiologycentre/annualreports/MortalityRiskAmongstVeryLowBirthWeightInfantsintheRepublicofIrelandReport2014-2016.pdf)

This notebook aims to sythesise data to reflect the findings in this report

# The Variables - Explained

## Gestational Weeks
Gestational age is the common term used during pregnancy to describe how far along the pregnancy is. It is measured in weeks, from the first day of the woman's last menstrual cycle to the current date. A normal pregnancy can range from 38 to 42 weeks. Infants born before 37 weeks are considered premature. The outcome of this variable will be most likely between 22 - 32 weeks.
(ref:https://medlineplus.gov/ency/article/002367.htm)

## Birthweight
Birth weight is the first weight of your baby, taken just after he or she is born. A low birth weight is less than 5.5 pounds. A high birth weight is more than 8.8 pounds. The expected result of this variable will see most weights less than 5.5 pounds 

## Congenital Anomaly 
Congenital anomalies are also known as birth defects, congenital disorders or congenital malformations. Yes or No.

## Disposition at 1 Year
Did the infant live or die.  The outcome is recorded one year after birth.  There are 4 possible outcomes:
- Died
- Home
- Still Hospitalised
- Unkown
 



In [1]:
# create a dataframe structure by starting with the column headings
import pandas as pd
import numpy as np
df = pd.DataFrame(columns= ["Gestational Weeks", "Birthweight", "Congenital Anomaly", "Disposition at 1 Year" ])

In [2]:
df

Empty DataFrame
Columns: [Gestational Weeks, Birthweight, Congenital Anomaly, Disposition at 1 Year]
Index: []

In [3]:
# Testing to populate the data 
data = [['Alex',10, 6, 2],['Bob',12, 6 ,2],['Clarke',13, 6 ,2]]
df = pd.DataFrame(data, columns = ['Gestational Weeks', 'Birthweight', 'Congenital Anomaly', 'Disposition at 1 Year'])
df

Gestational Weeks  Birthweight  Congenital Anomaly  Disposition at 1 Year
0              Alex           10                   6                      2
1               Bob           12                   6                      2
2            Clarke           13                   6                      2

In [4]:
# The above table is the basic structure which I will use as the foundations for systhessing my dataset

## Gestational Weeks
In this dataset the Gestational weeks has a spread from 21 weeks to 33 weeks.


In [15]:
#Setting Parameters for gestational weeks.  Majority of babies born weeks 28, 29, 30
#mean and standard deviation
gw = np.random.normal(28, 3, 100) 
gw

array([27.28374966, 27.11436421, 28.83285777, 28.43391385, 32.76732991,
       28.54663024, 23.59578202, 30.58289479, 25.21698127, 30.72466917,
       31.03235284, 25.62102174, 29.18301839, 26.24063681, 30.10093838,
       32.8355771 , 25.1757161 , 29.06805246, 26.71895864, 29.88942889,
       25.61695929, 28.33759611, 27.00089004, 24.74869085, 28.83255365,
       31.51155213, 31.20023436, 26.80407618, 27.31968119, 27.07360231,
       29.57455842, 24.04602939, 21.52165549, 29.61088893, 24.59027198,
       28.1623706 , 23.43103028, 23.19540318, 30.47392753, 23.35836628,
       29.09500204, 28.85033064, 26.216758  , 30.72424835, 27.93346283,
       28.71708434, 31.27107864, 25.03800878, 29.49582361, 30.78990796,
       32.69619078, 26.26491476, 26.59515577, 29.26601736, 23.29547342,
       30.70568328, 30.56201538, 29.30287212, 23.15097227, 24.27850177,
       27.47974237, 32.03976291, 29.75362941, 29.44841697, 30.91033208,
       26.09480173, 29.56306313, 32.80142964, 26.02939326, 27.90

## Birthweight
The birth weights of very low birth weight infants ranged from
360g to 2,640g

In [16]:
#Setting Parameters for bithweight, low = 400g, High = 1500g

bw = np.random.randint(400, 1500, size=100) #this function draws random numbers from a uniform distribution
bw

array([ 525, 1214,  539,  421, 1137,  502, 1319, 1423,  929,  628, 1328,
       1093,  455, 1067,  855,  949,  865, 1277, 1473,  924,  770, 1330,
        400,  659, 1351, 1357, 1468,  797, 1229,  748,  575, 1281, 1193,
       1436,  744, 1357,  562, 1245, 1431, 1168, 1232,  692, 1213, 1105,
        899, 1066,  843,  537, 1268,  641, 1161,  757,  525, 1277, 1437,
        551,  504, 1004, 1075, 1229,  903,  409,  683, 1084,  699,  684,
        672,  442, 1177, 1454, 1090,  651, 1171,  925,  623, 1253,  987,
        859,  848,  903,  404,  936,  429,  768,  502,  602, 1451, 1442,
        457, 1186, 1152, 1494, 1080, 1113,  513, 1194,  814, 1245,  666,
        429])

## Congenital Anomaly
About 9% of babies have a congenital anomaly.  Does the baby have a congenital anomaly? No = 0, Yes = 1  

In [25]:
# using random.choice, I have implmented a bias to reflect the real world
ca = np.random.choice([0,1], 100, p=[0.9, 0.1])
ca


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

## Disposition at 1 Year


In [29]:
dip = np.random.choice([0, 1, 2, 3], 100, p=[0.2, 0.1, 0.1, 0.6])
dip

array([3, 3, 3, 0, 3, 0, 3, 3, 3, 2, 0, 1, 2, 3, 3, 3, 3, 1, 2, 3, 1, 3,
       3, 3, 3, 3, 3, 3, 1, 3, 3, 2, 3, 3, 1, 0, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 2, 0, 3, 3, 3, 0, 3, 3, 3, 3,
       3, 3, 0, 3, 3, 0, 3, 3, 3, 3, 0, 0, 3, 2, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 1, 3, 3, 3, 0, 3, 3, 3, 3, 0])

# Creating the Dataset

In [30]:
# Populating the Dataset

df = pd.DataFrame({"Gestational Weeks" : gw, "Birthweight" : bw, "Congenital Anomaly" : ca, "Disposition" : dip})
df

Gestational Weeks  Birthweight  Congenital Anomaly  Disposition
0           27.283750          525                   0            3
1           27.114364         1214                   0            3
2           28.832858          539                   0            3
3           28.433914          421                   0            0
4           32.767330         1137                   0            3
5           28.546630          502                   0            0
6           23.595782         1319                   0            3
7           30.582895         1423                   0            3
8           25.216981          929                   0            3
9           30.724669          628                   0            2
10          31.032353         1328                   0            0
11          25.621022         1093                   0            1
12          29.183018          455                   0            2
13          26.240637         1067                   0            3
14          30.100938          855                   0            3
15          32.835577          949                   0            3
16          25.175716          865                   0            3
17          29.068052         1277                   0            1
18          26.718959         1473                   0            2
19          29.889429          924                   0            3
20          25.616959          770                   0            1
21          28.337596         1330                   0            3
22          27.000890          400                   0            3
23          24.748691          659                   0            3
24          28.832554         1351                   0            3
25          31.511552         1357                   0            3
26          31.200234         1468                   0            3
27          26.804076          797                   1            3
28          27.319681         1229                   0            1
29          27.073602          748                   1            3
..                ...          ...                 ...          ...
70          23.323670         1090                   0            3
71          25.249673          651                   1            0
72          28.078702         1171                   1            3
73          30.239691          925                   0            3
74          32.059977          623                   0            3
75          26.307456         1253                   0            3
76          22.212512          987                   0            0
77          25.558102          859                   0            0
78          27.563211          848                   0            3
79          24.399276          903                   0            2
80          22.287866          404                   1            1
81          30.675295          936                   0            3
82          31.153843          429                   0            3
83          27.325404          768                   0            3
84          27.820559          502                   0            3
85          28.554924          602                   0            3
86          33.260433         1451                   0            3
87          21.326581         1442                   0            3
88          31.970353          457                   0            3
89          28.321544         1186                   0            3
90          27.695884         1152                   0            1
91          32.407416         1494                   0            3
92          27.964200         1080                   0            3
93          24.852991         1113                   0            3
94          30.545304          513                   0            0
95          21.709426         1194                   1            3
96          28.795093          814                   0      